### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by ofhouse** [dealmore/terraform-aws-next-js-image-optimization#1]
This is a tracking issue for the upcoming `v1.0` release of this module.

## ToDo

- [x] Add tests for all supported file-types
  - [x]  jpeg
  - [x] png
  - [x] svg
  - [x] gif
  - [x] Webp
- [x] Release `@dealmore/terraform-next-node-bridge` as a shared dependency
- [x] Add e2e tests (The tooling used for this in the tf-next package should be outsourced into a shared module for this)
- [ ] Output of a CloudFront Origin group (for using the module in an existing CloudFront distribution)
- [x] Option to suppress the creation of a new CloudFront distribution
- [x] Setup dependabot to automatically generate PRs for new versions of Next.js
- [ ] Use semantic release (or changesets) to build & distribute the component via npm
